version: '3.8'

services:
  db:
    image: postgres:18-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: plataforma_fepi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: django_backend
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=plataforma_fepi
      - DB_USER=admin
      - DB_PASSWORD=1234
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: node_frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: